# Generated by Django 5.0.7 on 2024-08-03 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_alumno', models.CharField(max_length=50, verbose_name='Nombre del curso')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('documento', models.CharField(max_length=50, verbose_name='Numero de documento')),
                ('email', models.CharField(max_length=50, verbose_name='Correo electronico')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del curso')),
                ('duracion', models.CharField(max_length=50, verbose_name='Duracion')),
                ('datos', models.CharField(max_length=50, verbose_name='Nombre y Apellido del profesor')),
            ],
        ),
        migrations.CreateModel(
            name='Trabajos_Practicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_de_entrega', models.DateField()),
                ('asignatura', models.CharField(max_length=50, verbose_name='Asignatura')),
            ],
        ),
    ]
